<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <Nullable>enable</Nullable>
        <AssemblyName>CodeModTemplate</AssemblyName>
        <RootNamespace>CodeModTemplate</RootNamespace>
        <OutputType>Library</OutputType>
    </PropertyGroup>

    <PropertyGroup>
        <GameDirectory>{{GameDirectory}}</GameDirectory>
        <GameAssembliesPath>$(GameDirectory)CardventureJustAHead_Data\Managed\</GameAssembliesPath>
    </PropertyGroup>

    <ItemGroup>
        <Reference Include="Assembly-CSharp">
            <HintPath>$(GameAssembliesPath)Assembly-CSharp.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="UnityEngine.CoreModule">
            <HintPath>$(GameAssembliesPath)UnityEngine.CoreModule.dll</HintPath>
            <Private>false</Private>
        </Reference>
    </ItemGroup>
</Project>
