<Project>
    <PropertyGroup>
        <ModOutputPath>$(MSBuildProjectDirectory)\out\CodeModTemplate</ModOutputPath>
    </PropertyGroup>
    
    <Target Name="PrepareModOutput" AfterTargets="CopyFilesToOutputDirectory">
        <RemoveDir Directories="$(ModOutputPath)" Condition="Exists('$(ModOutputPath)')" />
        <MakeDir Directories="$(ModOutputPath)" />
        <ItemGroup>
            <ModDlls Include="$(TargetDir)*.dll" />
        </ItemGroup>
        <Copy SourceFiles="@(ModDlls)" DestinationFolder="$(ModOutputPath)\CodeMods" />
        <ItemGroup>
            <AssetsToCopy Include="assets\**\*" />
        </ItemGroup>
        <Copy SourceFiles="@(AssetsToCopy)"
              DestinationFiles="@(AssetsToCopy->'$(ModOutputPath)\%(RecursiveDir)%(Filename)%(Extension)')"
              SkipUnchangedFiles="true" />
        <Message Importance="high" Text="Mod file copied." />
    </Target>
</Project>